version: '3.7'
services:
  php-fpm:
    image: php-fpm-nextcloud
    ports:
      - "9000:9000"
    volumes:
      - ./cloud:/srv
      - ./log/php:/var/log/php7
  nginx:
    image: hetsh/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cloud:/srv
      - ./host:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx