version: '3.7'
services:
  php-fpm:
    image: hetsh/php-fpm-nextcloud
    ports:
      - "9000:9000"
    volumes:
      - /tmp/cloud/data:/srv
      - /tmp/cloud/log_php:/var/log/php7
      - /etc/localtime:/etc/localtime:ro
  nginx:
    image: hetsh/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./host.conf:/etc/nginx/conf.d/host.conf:ro
      - /tmp/cloud/ssl:/etc/ssl
      - /tmp/cloud/data:/srv
      - /tmp/cloud/log_nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
