version: '3.7'
services:
  php-fpm:
    image: hetsh/php-fpm-nextcloud
    ports:
      - "9000:9000"
    volumes:
      - /tmp/cloud:/srv
      - /tmp/log/php:/var/log/php7
      - /etc/localtime:/etc/localtime:ro
  nginx:
    image: hetsh/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./host:/etc/nginx/conf.d
      - /tmp/cloud:/srv
      - /tmp/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro