version: '3.7'
services:
  php-fpm:
    image: hetsh/php-nextcloud
    volumes:
      - /root/cloud/data:/srv
      - /root/cloud/log_php:/var/log/php7
      - /etc/localtime:/etc/localtime:ro
  nginx:
    image: hetsh/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./host.conf:/etc/nginx/conf.d/default.conf:ro
      - /root/cloud/ssl:/etc/ssl
      - /root/cloud/data:/srv
      - /root/cloud/log_nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
  mariadb:
    image: hetsh/mariadb
    command:
      - --log-bin=binlog
    volumes:
      - ./mariadb.conf:/etc/my.cnf
      - /root/cloud/tables:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
