version: '3.7'
services:
  php-fpm:
    image: hetsh/php-fpm-nextcloud
    ports:
      - "9000:9000"
    volumes:
      - ./conf/php.ini:/etc/php7/php.ini:ro
      - ./conf/php-fpm.conf:/etc/php7/php-fpm.conf:ro
      - ./conf/www.conf:/etc/php7/php-fpm.d/www.conf:ro
      - /tmp/cloud:/srv
      - /tmp/log/php:/var/log/php7
      - /etc/localtime:/etc/localtime:ro
  nginx:
    image: hetsh/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./host:/etc/nginx/conf.d:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/cloud:/srv
      - /tmp/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro